import {
  FaDev,
  FaGithub,
  FaLinkedin,
  FaWhatsapp,
} from "react-icons/fa";

export const category = [
  "General",
  "Business",
  "Cryptocurrency",
  "Economy",
  "Finance",
  "Forex",
  "Markets",
  "Property",
  "Startup",
  "Entertainment",
  "Arts",
  "Books",
  "Celebrities",
  "Gaming",
  "Movies",
  "Music",
  "TV",
  "Lifestyle",
  "Autos",
  "Beauty",
  "Cooking",
  "Fitness",
  "Health",
  "Medication",
  "Religion",
  "Travel",
  "Politics",
  "Science",
  "Climate",
  "Education",
  "Environment",
  "Genetics",
  "Geology",
  "Physics",
  "Space",
  "Wildlife",
  "Sports",
  "Baseball",
  "Basketball",
  "Boxing",
  "Cricket",
  "F1",
  "Football",
  "Golf",
  "Hockey",
  "Nascar",
  "Rugby",
  "Soccer",
  "Tennis",
  "Volleyball",
  "Technology",
  "AI",
  "Computing",
  "CyberSec",
  "Gadgets",
  "Internet",
  "Mobile",
  "Robot",
  "VR",
  "World",
];

export const socialLinks = [
  {
    to: "https://www.linkedin.com/in/iamdipankarpaul/",
    label: "LinkedIn",
    icon: FaLinkedin,
    target: "_blank",
    ariaLabel: "Linkedin link",
  },
  {
    to: "https://github.com/dipankarpaul2k",
    label: "GitHub",
    icon: FaGithub,
    target: "_blank",
    ariaLabel: "Github link",
  },
  {
    to: "https://dev.to/dipankarpaul",
    label: "Dev.to",
    icon: FaDev,
    target: "_blank",
    ariaLabel: "Dev.to link",
  },
  {
    to: "https://wa.link/0y3avn",
    label: "WhatsApp",
    icon: FaWhatsapp,
    target: "_blank",
    ariaLabel: "Whatsapp link",
  },
];
